repos:
  # ruff (Lint & Format) setup
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10  # Use the latest version of ruff-pre-commit
    hooks:
      # execute Linter
      - id: ruff
        args: [ --fix ]
      # execute formatter
      - id: ruff-format

  # General code quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace    # remove trailing whitespace
      - id: end-of-file-fixer      # ensure file ends with a newline
      - id: check-yaml             # YAML file syntax check
      - id: check-added-large-files # check for large files added to the repository
        args: ["--maxkb=1000"]

  # mypy (Type Checking)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [ "--pretty" ]
